<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Crowd Writing--{{domain}}</title>
  <link href="stylesheets/app.css" rel="stylesheet" type="text/css"> 
  <link href="stylesheets/font-awesome.css" rel="stylesheet" type="text/css"> 
  <script src="javascripts/vendor/custom.modernizr.js"></script>
  <script>
  var require = { baseUrl : "javascripts", deps : [ "main"] };
  var Category = '{{controller}}';
  </script>
  <script src="javascripts/lib/require.js"></script>
</head>
<body>
  {{ include('/partical/nav.phtml') }}
  <section class="main"> 
    <div class="row collapse full">
      <div class="columns large-12">
        <div class="welcome">
          <img src='/img/welcome.jpg'>
          <h2>EVERYTHING YOU NEED IS</h2>
          <h2>WRITE</h2>
          <a class='button success' href='/user/new'>GET STARTED</a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="columns large-9">
        <h3 class='pure'>Hot Chapters</h3>
        <div class="chapters">
           {% for chapter in hotChapter %}
           <div class="chapter">
              <img src="{{ chapter.avatar }}"> <b><a href='/chapter/{{chapter.ChapterId}}'>{{chapter.ChapterTitle}}</a></b> <span class="time">{{chapter.UpdateTime}}</span>
                <div class="markdown">{{chapter.Summary}}</div>
                <span class="right"> <a href='/chapter/{{chapter.ChapterId}}'>READ MORE>> </a></span>
            </div>
           {% endfor %}
        </div>
      </div>
      <div class="columns large-3">
        <h3>Hot Users</h3>
        <ul class="users">
        {% for user in hotUsers %}
          <li>
            <figure>
            <img src="{{ user.avatar }}" class='{{user.relation}}'>

             <a href='/user/{{ user.UserId }}'>{{ user.UserName }}</a>
            </figure>
           
          </li>
        {% endfor %}
        </ul>
      </div>
    </div>
  
  </section> 

    {{ include('/partical/scripts.phtml') }}
    <script type="text/javascript" src="/javascripts/lib/Markdown.Converter.js"></script>
    <script type="text/javascript">
      var converter = new Markdown.Converter();
      $(document).ready(function() {
        $.each($('.markdown'), function(idx, item) {
          var text = $(item).html();
          html = converter.makeHtml(text);
          $(item).html(html);
        });
      });
      
   </script>
</body>
</html>
