<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>Crowd Writing--{{domain}}</title>
	<link href="/stylesheets/chapter.css" rel="stylesheet" type="text/css"> 
	<link href="/stylesheets/font-awesome.css" rel="stylesheet" type="text/css"> 
	<script src="/javascripts/vendor/custom.modernizr.js"></script>
  <script>
  var require = { baseUrl : "/javascripts", deps : [ "main"] };
  var Category = '{{controller}}';
  </script>
  <script src="/javascripts/lib/require.js"></script>
</head>
<body>
	<nav class="site-logo">
		<a href='/'><img src="/img/logo.png"></a>
	</nav>
	<article class="user">
		  {{ include('/partical/user.phtml') }}
	</article>
	<div class="container">
		<div class="surface">
			<div class="surface-inner">
				{% for chapter in Chapter %}
				<article>
					<section class="post-page-wrapper">
						<div class="post-page-inner">
							<div class="author">
								
								 <img src="{{ chapter.avatar }}" >
								 <a href='/user/{{chapter.UserId}}'>{{ chapter.UserName }}</a>
								 <div class="publish-time">
								 	<strong>Publiced</strong>
								 	<p>{{chapter.CreateTime}}</p>
								 	<strong>Updated</strong>
								 	<p>{{chapter.UpdateTime}}</p>
								 </div>

								
							</div>
							<div class="post-field">
								<h1>{{chapter.ChapterTitle}}</h1>
								<span class="time">{{chapter.UpdateTime}}</span>
								<div class="body markdown">{{chapter.ChapterContent}}</div>
								
								<div class="recommand">
									<div class="before"></div>
									<button class='medium success small-round'><i class="icon-ok-circle"></i> Recommanded</button>
									<div class="recommand-votes">
										<div class="vote-inner">
											14
										</div>
										<div class="vote-arrow"></div>
									</div>
									<div class="clf"></div>
								</div>
								
								

							</div>
						</div>
						<div class="post-comments">
							<div class="header">
								<span>Comments</span>
							</div>
							<div class="comment-list">
								{% for comment in Comments %}
								<div class="comment-body">
									<div class="comment-user">

										<a href='/Chapter/{{comment.UserId}}'><img src='{{comment.avatar}}' ></a>
									</div>
									<div class="comment-text">
										<div class="arrow"></div>
										<p>{{comment.CommentText}}</p>
										<span class="floor">{{loop.index}}</span>
										<span class="signature"><a href="/User/{{comment.UserId}}">{{comment.UserName}}</a></span>
									</div>
								</div>
								{% else %}
									<div class="empty"></div>
								{% endfor %}
								<div class="leave-comment">
									{% if userid %}
									<p>Leave your comment here</p>
									<form action="/Comment" method="post">
									<input type="hidden" value={{chapter.ChapterId}} name='ChapterId'>
									<input type="hidden" value={{token}} name="token">
									<textarea name='commentText'></textarea>
									<button class='right small small-round success'>Submit</button>
									</form>
									{% endif %}
								</div>
							</div>

						</div>
					</section>
					<footer>

					</footer>
				</article>
				{% endfor %}
			</div>
		</div>
	</div>
	{{ include('/partical/scripts.phtml') }}
	<script type="text/javascript" src="/javascripts/lib/Markdown.Converter.js"></script>
	<script type="text/javascript">
	var converter = new Markdown.Converter();
	$(document).ready(function() {
		$.each($('.markdown'), function(idx, item) {
			var text = $(item).html();
			html = converter.makeHtml(text);
			$(item).html(html);
		});
	});

	</script>
</body>
</html>